module.exports =  [
    
    {
      "id_user": 1,
      "name_user": "Administrador",
      "nick_user": "Admin",
      "login": "admin@epkweb.com",
      "password": "14f46eed8c373f040dbb98b3dd6b0ed5",
      "id_city": 1,
      "avatar": "admin.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "0",
      "last_accessed": "2023-10-23T14:29:01",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 2,
      "name_user": "Alexandra Leret",
      "nick_user": "Alexandra",
      "login": "alexandra@epkweb.com",
      "password": "6491394b4602ddf401a33bcec5a90e24",
      "id_city": 1,
      "avatar": "alexandra.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2021-02-24T14:14:52",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 3,
      "name_user": "Alvaro Roche",
      "nick_user": "Alvaro",
      "login": "aroche@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 4,
      "name_user": "Patrick Leret",
      "nick_user": "Patrick",
      "login": "pleret@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 5,
      "name_user": "Veronica Azpurua",
      "nick_user": "Veronica",
      "login": "vazpurua@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "veronica.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 6,
      "name_user": "David Ohana",
      "nick_user": "David",
      "login": "david@ohanasia.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 2,
      "avatar": "david.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "1",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 7,
      "name_user": "Annie Jo Oksness",
      "nick_user": "Annie",
      "login": "anniejo@ohanasia.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 2,
      "avatar": "annie.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "1",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 8,
      "name_user": "Carolina Duran",
      "nick_user": "Carolina",
      "login": "cduran@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "cduran.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 9,
      "name_user": "Patricia Pocaterra",
      "nick_user": "Patricia",
      "login": "ppocaterra@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "patricia.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 10,
      "name_user": "Nanda Castro",
      "nick_user": "Nanda",
      "login": "mcastro@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "nanda.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-06-15T13:41:28",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 11,
      "name_user": "Agente_old",
      "nick_user": "Agente_old",
      "login": "ohanasia@shopepk.com",
      "password": "d41d8cd98f00b204e9800998ecf8427e",
      "id_city": 2,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "1",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-12-14T11:29:41",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 12,
      "name_user": "Shirley",
      "nick_user": "Shirley",
      "login": "shirley@ohanasia.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 2,
      "avatar": "shirley.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "1",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 13,
      "name_user": "Soporte TIC",
      "nick_user": "Soporte",
      "login": "soporte@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 14,
      "name_user": "Spain",
      "nick_user": "Spain",
      "login": "spain@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "spain.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 3,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 15,
      "name_user": "Dominican Republic",
      "nick_user": "D Republic",
      "login": "drepublic@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "drepublic.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 4,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 16,
      "name_user": "Ecuador",
      "nick_user": "Ecuador",
      "login": "ecuador@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "ecuador.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 5,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 17,
      "name_user": "Colombia",
      "nick_user": "Colombia",
      "login": "colombia@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "colombia.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 6,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 18,
      "name_user": "Costa Rica",
      "nick_user": "C Rica",
      "login": "crica@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "crica.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 7,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 19,
      "name_user": "Honduras",
      "nick_user": "Honduras",
      "login": "honduras@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "honduras.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 8,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2015-06-01T15:19:10",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 20,
      "name_user": "Peru",
      "nick_user": "Peru",
      "login": "peru@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "peru.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 9,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 21,
      "name_user": "Panama",
      "nick_user": "Panama",
      "login": "panama@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "panama.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 10,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 22,
      "name_user": "Israel",
      "nick_user": "Israel",
      "login": "israel@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "israel.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 11,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 23,
      "name_user": "Aruba",
      "nick_user": "Aruba",
      "login": "aruba@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "aruba.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 12,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 24,
      "name_user": "Brazil",
      "nick_user": "Brazil",
      "login": "brazil@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "brazil.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 13,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 25,
      "name_user": "Chile",
      "nick_user": "Chile",
      "login": "chile@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "chile.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 14,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 26,
      "name_user": "Gabriela van Eerdewijk",
      "nick_user": "Gabriela",
      "login": "gvan@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "gvan.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-05-30T11:35:01",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 27,
      "name_user": "Andrea Vaamonde",
      "nick_user": "Andrea V",
      "login": "avaamonde@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 28,
      "name_user": "Madeleine Diaz",
      "nick_user": "Madeleine",
      "login": "mdiaz@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 29,
      "name_user": "Mariana Valedon",
      "nick_user": "Mariana",
      "login": "mvaledon@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "mvaledon.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2015-06-17T16:27:48",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 30,
      "name_user": "Andrea Padula",
      "nick_user": "Andrea P",
      "login": "apadula@epkweb.com",
      "password": "95f6eba14413c97e6a5afbc87ab38b9a",
      "id_city": 1,
      "avatar": "apadula.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2018-11-20T11:25:12",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 31,
      "name_user": "Mathias Montassier",
      "nick_user": "Mathias",
      "login": "mmontassier@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 32,
      "name_user": "Adriana Andrade",
      "nick_user": "Adriana",
      "login": "aandrade@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "aandrade.jpg",
      "edit": "0",
      "edit_catalog": "1",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 33,
      "name_user": "Sonia Galavis",
      "nick_user": "Sonia",
      "login": "sgalavis@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 34,
      "name_user": "John Lobato",
      "nick_user": "John",
      "login": "jlobato@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 35,
      "name_user": "Hector Yepez",
      "nick_user": "Hector",
      "login": "hyepez@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 36,
      "name_user": "Gabriel Gasco",
      "nick_user": "Gabriel",
      "login": "ggasco@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 37,
      "name_user": "Christian Ortiz",
      "nick_user": "Christian",
      "login": "cortiz@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "1",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 38,
      "name_user": "Karen Torres",
      "nick_user": "Karen",
      "login": "ktorres@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "karen.jpg",
      "edit": "0",
      "edit_catalog": "1",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-05-19T14:37:00",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 39,
      "name_user": "Samuel Fernandez",
      "nick_user": "Samuel",
      "login": "sfernandez@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 40,
      "name_user": "Anais Jimenez",
      "nick_user": "Anais",
      "login": "ajimenez@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 41,
      "name_user": "Ana Federica Payares",
      "nick_user": "Kika",
      "login": "apayares@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 42,
      "name_user": "Daniela",
      "nick_user": "Daniela",
      "login": "janinedanielac@gmail.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 43,
      "name_user": "Ana Karina Pavan",
      "nick_user": "Ana Karina",
      "login": "apavan@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "apavan.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 44,
      "name_user": "Luis Ernesto Gonzalez",
      "nick_user": "Luis",
      "login": "lgonzalez@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 45,
      "name_user": "Michelle Kovacs",
      "nick_user": "Michelle",
      "login": "mkovacs@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "michelle.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-06-12T15:19:27",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 46,
      "name_user": "Cesar Ruiz",
      "nick_user": "Cesar",
      "login": "cruiz@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 47,
      "name_user": "Luis Ferro",
      "nick_user": "Ferro",
      "login": "lferro@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 48,
      "name_user": "Agustin Ascanio",
      "nick_user": "Agustin",
      "login": "aascanio@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 49,
      "name_user": "Celeste Peñalver",
      "nick_user": "Celeste",
      "login": "cpenalver@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 50,
      "name_user": "Ana Elena Perez",
      "nick_user": "Ana Elena",
      "login": "aperez@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "anaelena.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 51,
      "name_user": "Diego Palacios",
      "nick_user": "Diego",
      "login": "dpalacios@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 52,
      "name_user": "Verónica Lázaro",
      "nick_user": "Veronica",
      "login": "vlazaro@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 53,
      "name_user": "Manuel Valdez",
      "nick_user": "Manuel",
      "login": "mvaldez@shopepk.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 54,
      "name_user": "Karla Rivera",
      "nick_user": "Karla",
      "login": "krivera@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 55,
      "name_user": "Jose Miguel Rojas",
      "nick_user": "Jose",
      "login": "jrojas@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 57,
      "name_user": "Mariana Mendoza",
      "nick_user": "Mariana",
      "login": "mmendoza@epkweb.com",
      "password": "f62068dcf13340363f15828a55590b4e",
      "id_city": 1,
      "avatar": "mmendoza.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2019-08-19T18:13:59",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 58,
      "name_user": "Andreina Carballo",
      "nick_user": "Andreina",
      "login": "acarballo@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "acarvallo.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2015-07-28T16:59:54",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 59,
      "name_user": "Guatemala",
      "nick_user": "Guatemala",
      "login": "guatemala@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "guatemala.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 15,
      "access_master": "0",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 60,
      "name_user": "Pedro Talavera",
      "nick_user": "Pedro",
      "login": "ptalavera",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 61,
      "name_user": "Giselle Azpurua",
      "nick_user": "Giselle",
      "login": "gazpurua@epkweb.com",
      "password": "6f38d35b73557fc70837dd63ba801513",
      "id_city": 1,
      "avatar": "gazpurua.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-11-22T14:31:25",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 62,
      "name_user": "Wilmer Flores",
      "nick_user": "Wilmer",
      "login": "wflores@epkweb.com",
      "password": "427fbfc2a15b2d5cdafb612f63cc5625",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 63,
      "name_user": "Karla Goncalves",
      "nick_user": "Karla",
      "login": "kgoncalves@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "kgoncalves.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2016-09-30T11:01:28",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 64,
      "name_user": "Maria Eugenia Reyna",
      "nick_user": "Maria Eugenia",
      "login": "mreyna@epkweb.com",
      "password": "d36e2d494d67da56c843b0b6e6e841d9",
      "id_city": 1,
      "avatar": "mreyna.jpg",
      "edit": "1",
      "edit_catalog": "0",
      "comment": "1",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-12-14T11:33:17",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 65,
      "name_user": "Ronald Perez",
      "nick_user": "Ronald",
      "login": "rperez@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2016-02-19T11:44:37",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 66,
      "name_user": "Eva Perez Ramos ",
      "nick_user": "Eva ",
      "login": "eperez@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2016-06-30T16:32:57",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 67,
      "name_user": "OyS",
      "nick_user": "OyS",
      "login": "jdelgado@epkweb.net",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": null,
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 68,
      "name_user": "Estefania Villasmil",
      "nick_user": "Estefania",
      "login": "evillasmil@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2016-08-19T10:33:03",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 69,
      "name_user": "Eugenia Bustamante",
      "nick_user": "Eu",
      "login": "ebustamante@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "ebustamante.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-09-01T12:19:04",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 70,
      "name_user": "Andreina Vogeler",
      "nick_user": "Andreina",
      "login": "avogeler@epkweb.com",
      "password": "3ddeceaf96d9cf80c6b64a9f58f9f029",
      "id_city": 1,
      "avatar": "avogeler.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-10-05T17:56:03",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 71,
      "name_user": "Master",
      "nick_user": "Developer",
      "login": "serviciosweb@epkweb.com",
      "password": "eea7a5c65332c6a5c41c35f857b7b5d7",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "0",
      "last_accessed": "2019-04-02T09:44:19",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 72,
      "name_user": "Laura Feo",
      "nick_user": "Laura",
      "login": "lfeo@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "lfeo.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-06-28T15:13:05",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 73,
      "name_user": "Maria Cristina Vallenilla",
      "nick_user": "Maria Cristina",
      "login": "mvallenilla@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "mvallenilla.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-10-03T17:20:28",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 74,
      "name_user": "Luis Fuentes ",
      "nick_user": "Luis",
      "login": "lfuentes@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "1",
      "last_accessed": "2017-07-19T13:23:27",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 75,
      "name_user": "Daniela Dioguardi ",
      "nick_user": "Daniela",
      "login": "ddioguardi@epkweb.com",
      "password": "b795dc57624bb2107597dca4abbc7039",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2017-09-26T11:30:52",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 78,
      "name_user": "Ionas Scheneider",
      "nick_user": "ionas",
      "login": "ionas.schneider@gmail.com",
      "password": "e10adc3949ba59abbe56e057f20f883e",
      "id_city": 1,
      "avatar": "ischneider.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "1",
      "last_accessed": "2017-06-29T09:06:36",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 79,
      "name_user": "Luis Guevara",
      "nick_user": "lguevara",
      "login": "lguevara@epkweb.com",
      "password": "46ac4b108904ac80be6bbea91e62673d",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2019-05-31T14:51:54",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 80,
      "name_user": "Andreina Vogeler",
      "nick_user": "Andreina",
      "login": "avogeler@epkweb.com",
      "password": "e6783ce2453fa070889a248262f55257",
      "id_city": 1,
      "avatar": "avogeler.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2018-11-12T13:56:51",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 81,
      "name_user": "Maria Cristina Vallenilla",
      "nick_user": "mvallenilla",
      "login": "mvallenilla@epkweb.net",
      "password": "b683f99b7b2fb67f0d10ff0e2edeb832",
      "id_city": 1,
      "avatar": "mvallenilla.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-07-12T17:45:44",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 82,
      "name_user": "Proveedor",
      "nick_user": "Proveedor",
      "login": "proveedor",
      "password": "7e2ca8af6b8bcb355d81aeb98cd7e1f3",
      "id_city": 2,
      "avatar": "",
      "edit": "0",
      "edit_catalog": "0",
      "comment": "0",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2019-04-02T09:49:27",
      "export_collection": "0",
      "export_drawings": "0"
    },
    {
      "id_user": 83,
      "name_user": "Agente",
      "nick_user": "agente",
      "login": "agente@epkweb.com",
      "password": "9a4e9460e77937a98f441f8cdcb596ac",
      "id_city": 2,
      "avatar": "",
      "edit": "0",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-11-28T01:33:07",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 84,
      "name_user": "Claudia Sabater",
      "nick_user": "Claudia",
      "login": "csabater@epkweb.com",
      "password": "afece0908217ac8956a8e59089f0456d",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2018-07-13T11:53:54",
      "export_collection": null,
      "export_drawings": null
    },
    {
      "id_user": 85,
      "name_user": "Isabel Borjas",
      "nick_user": "Isabel",
      "login": "iborjas@epkweb.com",
      "password": "bfe9292888575c1ae9cfed13bc91d7e2",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-11-28T09:06:06",
      "export_collection": "1",
      "export_drawings": null
    },
    {
      "id_user": 86,
      "name_user": "Alexandra Terrero",
      "nick_user": "Alexandra",
      "login": "aterrero@epkweb.com",
      "password": "7c018a343a71c470866bc7b503c5e962",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2018-09-05T17:21:11",
      "export_collection": null,
      "export_drawings": null
    },
    {
      "id_user": 87,
      "name_user": "Ane Azpiritxaga",
      "nick_user": "Ane",
      "login": "aazpiritxaga@epkweb.com",
      "password": "1809bdfa554ef8bbc6f29c02deb68d69",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2020-11-26T07:15:45",
      "export_collection": null,
      "export_drawings": null
    },
    {
      "id_user": 88,
      "name_user": "Daniela Assef",
      "nick_user": "Daniela",
      "login": "dassef@epkweb.com",
      "password": "40d8530db0dbb30e49a23e378eb77725",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2018-12-05T13:10:31",
      "export_collection": null,
      "export_drawings": null
    },
    {
      "id_user": 89,
      "name_user": "Andreina Torres",
      "nick_user": "Andreina",
      "login": "atorres@epkweb.com",
      "password": "91f4e2d9e185a93158c5f67068d85471",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2019-10-17T10:15:27",
      "export_collection": "1",
      "export_drawings": null
    },
    {
      "id_user": 90,
      "name_user": "Mariana Mendoza",
      "nick_user": "Mariana",
      "login": "mmendoza@epkweb.com",
      "password": "4c4c27fddfad5da351574c754f64b320",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2020-09-29T12:40:30",
      "export_collection": null,
      "export_drawings": null
    },
    {
      "id_user": 91,
      "name_user": "Agente 2",
      "nick_user": "agent2",
      "login": "agente2@epkweb.com",
      "password": "ceba7ba07aa8437374abb259f0ad83bb",
      "id_city": 2,
      "avatar": "",
      "edit": "0",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "0",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "0",
      "access_misc": "0",
      "access_orderform": "0",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-11-14T02:20:27",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 92,
      "name_user": "Andrea Raffalli",
      "nick_user": "araffalli",
      "login": "araffalli@epkweb.com",
      "password": "b683f99b7b2fb67f0d10ff0e2edeb832",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-11-15T14:10:26",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 93,
      "name_user": "Eugenia Padula",
      "nick_user": "Padula",
      "login": "epadula@epkweb.com",
      "password": "788de6fde1e8d18d886ce4fb62d74500",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2019-07-26T11:45:37",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 94,
      "name_user": "Ana Elisa Azpurua",
      "nick_user": "azpurua",
      "login": "azpurua@epkweb.com",
      "password": "9f5d53cb497c4032d22f33273a310ebc",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-10-02T16:43:55",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 95,
      "name_user": "Daniela LÃ³pez",
      "nick_user": "dlopez",
      "login": "dlopez@epkweb.com",
      "password": "7dfb289c34fe8443a582b9a5c0699956",
      "id_city": 1,
      "avatar": "",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-11-24T13:54:38",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 96,
      "name_user": "Alesia Hernandez",
      "nick_user": "ahernandez",
      "login": "ahernandez@epkweb.com",
      "password": "023a1e3951e7db7436a4164e4690af2d",
      "id_city": 1,
      "avatar": "ahernandez.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2022-12-16T10:27:40",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 97,
      "name_user": "Daniela Navarro",
      "nick_user": "dnavarro",
      "login": "dnavarro@epkweb.com",
      "password": "2d908636771f1fa23d60e8e8194374d0",
      "id_city": 1,
      "avatar": "dnavarro.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2020-06-29T13:08:26",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 98,
      "name_user": "Isabella Oropeza",
      "nick_user": "ioropeza ",
      "login": "ioropeza@epkweb.com",
      "password": "81dc9bdb52d04dc20036dbd8313ed055",
      "id_city": 1,
      "avatar": "ioropeza.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "0",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2021-06-25T14:45:48",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 99,
      "name_user": "Francesca Zumbo",
      "nick_user": "Francesca",
      "login": "fzumbo@epkweb.com",
      "password": "6304c707c0e7ed0bd38e39093a08bab9",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-10-23T15:55:17",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 100,
      "name_user": "Eugenia Ruiz",
      "nick_user": "Eugenia",
      "login": "eruiz@epkweb.com",
      "password": "5d867b25824ca79e04e252f66c22c194",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2022-09-26T11:04:36",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 101,
      "name_user": "Maria Laura Liberatore",
      "nick_user": "Maria Laura",
      "login": "mliberatore@epkweb.com",
      "password": "10a59ecb705fa3dceb21fd8c91884f71",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "1",
      "last_accessed": "2021-10-21T15:42:19",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 102,
      "name_user": "Marielisa Zafrane",
      "nick_user": "Marielisa",
      "login": "mzafrane@epkweb.com",
      "password": "10a59ecb705fa3dceb21fd8c91884f71",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2021-11-19T08:50:29",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 103,
      "name_user": "Ana Carolina Pacheco",
      "nick_user": "Ana Carolina",
      "login": "apacheco@epkweb.com",
      "password": "10a59ecb705fa3dceb21fd8c91884f71",
      "id_city": 1,
      "avatar": "default1.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-04-03T10:28:00",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 104,
      "name_user": "Camila Raffalli",
      "nick_user": "Camila",
      "login": "craffalli@epkweb.com",
      "password": "b683f99b7b2fb67f0d10ff0e2edeb832",
      "id_city": 1,
      "avatar": "defaultl.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-11-27T10:30:56",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 105,
      "name_user": "Ana Luisa Hoyos",
      "nick_user": "Ana",
      "login": "ahoyos@epkweb.com",
      "password": "84a32d4f38c552e39fc8987255068945",
      "id_city": 1,
      "avatar": "defaultl.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "0",
      "edit_freightinv": "0",
      "deprecated": "0",
      "last_accessed": "2023-11-15T16:07:19",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 106,
      "name_user": "Dev",
      "nick_user": "Dev",
      "login": "dev@epkweb.net",
      "password": "6304c707c0e7ed0bd38e39093a08bab9",
      "id_city": 1,
      "avatar": "default.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "0",
      "last_accessed": "2023-11-24T14:37:07",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 107,
      "name_user": "Carlota Huen",
      "nick_user": "Carlota",
      "login": "chuen@epkweb.com",
      "password": "b683f99b7b2fb67f0d10ff0e2edeb832",
      "id_city": 1,
      "avatar": "default.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "0",
      "last_accessed": "2023-11-10T15:48:18",
      "export_collection": "1",
      "export_drawings": "1"
    },
    {
      "id_user": 108,
      "name_user": "Maria Virginia",
      "nick_user": "M. Virginia",
      "login": "mfreites@epkweb.com",
      "password": "b683f99b7b2fb67f0d10ff0e2edeb832",
      "id_city": 1,
      "avatar": "default.jpg",
      "edit": "1",
      "edit_catalog": "1",
      "comment": "1",
      "translate": "1",
      "id_country": 1,
      "access_master": "1",
      "access_catalog": "1",
      "access_statistics": "1",
      "access_misc": "1",
      "access_orderform": "1",
      "edit_orderform": "1",
      "access_freightinv": "1",
      "edit_freightinv": "1",
      "deprecated": "0",
      "last_accessed": "2023-11-13T14:33:58",
      "export_collection": "1",
      "export_drawings": "1"
    }
  ];